### ISSUE TITLE
Missing asset error

### ISSUE THREAD

**Issue by bryanburress** [chesapeaketechnology/syncmonkey#1]
App is building great. Getting an error on start. Missing rclone.conf
![Screenshot_20191101-191516_Sync Monkey](https://user-images.githubusercontent.com/8942220/68046392-0e093580-fcdc-11e9-980a-119d3648bb8c.jpg)
 in asset directory

**Comment by christianrowlands** [comment]
I will message you via Slack with instructions on how to setup the rclone.conf.
